export const PROPERTIES = [
  {
    id: 1,
    title: "Casa Luxury",
    location: "AlphaVille, Juiz de Fora - MG",
    price: "R$ 3.500.000,00",
    beds: 5,
    baths: 7,
    parking: 6,
    area: "850m²",
    image: "https://i.imgur.com/pe07Ikg.png",
    category: "Imóvel em Condomínio",
    categorySlug: "imovel-em-condominio",
    code: "EF3OTO",
    listingType: "venda",
    condoFee: "R$ 1.500,00",
    iptu: "R$ 8.000,00"
  },
  {
    id: 2,
    title: "Residencial Horizonte",
    location: "AlphaVille, Juiz de Fora - MG",
    price: "R$ 8.900.000,00",
    beds: 4,
    baths: 5,
    parking: 3,
    area: "420m²",
    image: "https://i.imgur.com/pe07Ikg.png",
    category: "Apartamento em Condomínio",
    categorySlug: "apartamento-em-condominio",
    code: "RH2HOR",
    listingType: "venda"
  },
  {
    id: 3,
    title: "Villa Toscana",
    location: "AlphaVille, Juiz de Fora - MG",
    price: "R$ 4.200.000,00",
    beds: 3,
    baths: 4,
    parking: 4,
    area: "310m²",
    image: "https://i.imgur.com/pe07Ikg.png",
    category: "Imóvel na Planta",
    categorySlug: "imovel-na-planta",
    code: "VT3TOS",
    listingType: "venda"
  },
  {
    id: 4,
    title: "Cobertura Diamond",
    location: "AlphaVille, Juiz de Fora - MG",
    price: "R$ 15.000.000,00",
    beds: 4,
    baths: 6,
    parking: 5,
    area: "600m²",
    image: "https://i.imgur.com/pe07Ikg.png",
    category: "Imóveis Em Alta",
    categorySlug: "imoveis-em-alta",
    code: "CD4DIA",
    listingType: "venda"
  },
  {
    id: 5,
    title: "Terreno Alpha",
    location: "AlphaVille, Juiz de Fora - MG",
    price: "R$ 850.000,00",
    beds: 0,
    baths: 0,
    parking: 0,
    area: "1200m²",
    image: "https://i.imgur.com/W10YtDm.png",
    category: "Somente Terreno",
    categorySlug: "somente-terreno",
    code: "TA5ALP",
    listingType: "venda"
  },
  {
    id: 6,
    title: "Apartamento Garden",
    location: "São Mateus, Juiz de Fora - MG",
    price: "R$ 1.200.000,00",
    beds: 3,
    baths: 2,
    parking: 2,
    area: "180m²",
    image: "https://i.imgur.com/pe07Ikg.png",
    category: "Apartamento em Condomínio",
    categorySlug: "apartamento-em-condominio",
    code: "AG6GAR",
    listingType: "venda"
  },
  {
    id: 7,
    title: "Casa de Campo",
    location: "Granbery, Juiz de Fora - MG",
    price: "R$ 4.500,00 / mês",
    beds: 4,
    baths: 3,
    parking: 4,
    area: "450m²",
    image: "https://i.imgur.com/pe07Ikg.png",
    category: "Imóvel para Aluguel",
    categorySlug: "imovel-para-aluguel",
    code: "CC7CAM",
    listingType: "aluguel",
    condoFee: "R$ 800,00",
    iptu: "R$ 250,00",
    insurance: "R$ 120,00"
  }
];
